name: swd_group_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  another_flushbar: ^1.10.26
  shared_preferences: ^2.0.8
  cached_network_image: ^3.0.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  connectivity_plus: ^3.0.3
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo.png
    - lib/images/default-product.jpg
